"""Add modifiers

Revision ID: 207d224e7bd3
Revises: 415e47b1e1f1
Create Date: 2026-09-22 22:52:33.206925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '207d224e7bd3'
down_revision: Union[str, Sequence[str], None] = '415e47b1e1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modifier_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('restaurant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_selections', sa.Integer(), nullable=False),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_adjustment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['modifier_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_modifier_groups',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('modifier_group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_group_id'], ['modifier_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'modifier_group_id')
    )
    op.create_table('order_item_modifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('modifier_id', sa.Uuid(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('price_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        "order_items",
        sa.Column(
            "total_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE order_items
        SET total_price = unit_price * quantity
        WHERE total_price IS NULL
        """
    )

    op.alter_column(
        "order_items",
        "total_price",
        existing_type=sa.Numeric(precision=10, scale=2),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'total_price')
    op.drop_table('order_item_modifiers')
    op.drop_table('product_modifier_groups')
    op.drop_table('modifiers')
    op.drop_table('modifier_groups')
    # ### end Alembic commands ###
